---
- name: Converge
  hosts: all
  become: true

  tasks:  
    - name: Install depends
      ansible.builtin.apt:
        name: python3-pip
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Install depends RHEL
      ansible.builtin.package:
        name:
          - epel-release
          - python-pip
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install pexpect python package
      ansible.builtin.pip:
        name: 
          - pexpect
          - urllib3
          - pyOpenSSL
          - ndg-httpsclient
          - pyasn1
        
    
    - name: Make install directory 
      ansible.builtin.shell:
        cmd: mkdir -p /home/user/

    - name: Download sctipt
      ansible.builtin.get_url:
        url: https://download.onlyoffice.com/install/workspace-install.sh
        dest: /home/user/
        mode: '0440'
      become: yes

    - name: Run install srcipt
      ansible.builtin.expect: 
        command: /bin/bash /home/user/workspace-install.sh --skiphardwarecheck true
        responses: 
          "Install with Docker [Y/N/C]?": 'N'
      register: info
      become: yes 

    - ansible.builtin.debug:
        msg: "{{ info.stdout }}"
