---
- name: Converge
  hosts: all
  become: true

  tasks:    
    - name: Make install directory 
      ansible.builtin.shell:
        cmd: mkdir -p /home/user/

    - name: Download sctipt
      ansible.builtin.get_url:
        url: https://download.onlyoffice.com/install/workspace-install.sh
        dest: /home/user/
        mode: '0440'
        validate_certs: no
      become: yes

    - name: Run install srcipt
      ansible.builtin.expect: 
        command: /bin/bash /home/user/workspace-install.sh --skiphardwarecheck true
        responses: 
          "Install with Docker [Y/N/C]?": 'N'
      register: info
      become: yes 

    - ansible.builtin.debug:
        msg: "{{ info.stdout }}"
