---
- name: Converge
  hosts: all
  become: true

  tasks:  
    - name: Install depends RHEL
      ansible.builtin.package:
        name:
          - epel-release
          - python-pip
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install pexpect python package
      ansible.builtin.pip:
        name: 
          - pexpect
      when: ansible_os_family == "RedHat"
    
    - name: Make install directory 
      ansible.builtin.shell:
        cmd: mkdir -p /home/user/

    - name: Download sctipt
      ansible.builtin.get_url:
        url: https://download.onlyoffice.com/install/workspace-install.sh
        dest: /home/user/
        mode: '0440'
        validate_certs: no
      become: yes

    - name: Run install srcipt
      ansible.builtin.shell:
        cmd: echo "N" | bash /home/user/workspace-install.sh --skiphardwarecheck true
      register: info

    - ansible.builtin.debug:
        msg: "{{ info.stdout }}"
