---
- name: Converge
  hosts: all
  become: true

  tasks:  
  # - name: Create script directory if it does not exist
  #    ansible.builtin.file:
  #      path: /home/user
  #      state: directory
  #      mode: '0755'

    - name: Download sctipt
      ansible.builtin.get_url:
        url: https://download.onlyoffice.com/install/workspace-install.sh
        dest: /home/vagrant/
        mode: '0440'
        validate_certs: no
      become: yes

    - name: remove postfix
      ansible.builtin.apt:
        name: postfix
        state: absent
      when: ansible_os_family == "Debian"

    - name: Run install srcipt
      ansible.builtin.shell:
        cmd: echo "N" | bash /home/vagrant/workspace-install.sh --skiphardwarecheck true --makeswap false


    ####################################
    #                                  # 
    #  Healthcheck all services below  #
    #                                  #
    ####################################

    #- name: Check service status 
         
