---
- name: Converge
  hosts: all
  become: true

  tasks:  
    - name: Create script directory if it does not exist
      ansible.builtin.file:
        path: /home/user
        state: directory
        mode: '0755'

    - name: Download sctipt
      ansible.builtin.get_url:
        url: https://download.onlyoffice.com/install/workspace-install.sh
        dest: /home/user/
        mode: '0440'
        validate_certs: no
      become: yes

    - name: Run install srcipt
      ansible.builtin.shell:
        cmd: echo "N" | bash workspace-install.sh --skiphardwarecheck true --makeswap false
      register: info
      args:
        chdir: /home/user/

    - ansible.builtin.debug:
        msg: "{{ info.stdout }}"

    ####################################
    #                                  # 
    #  Healthcheck all services below  #
    #                                  #
    ####################################

    - name: Check service status 
         
