name: check matrix

on:
  push:
  
  
env:
  COMPANY_NAME: "danilaworker"
  PRODUCT_NAME: "documentserver" 
  
jobs:
  build:
    name: Check docker manifest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compose: [ "postgresql.yaml" ]
        variables: [ "POSTGRESQL_VERSION=9 IMMORTAL=FOO ANOTHER=BOO" ]
        include: 
          - compose: "postgresql.yaml" 
            variables: "POSGRESQL_VERSION=10 IMMORTAL=DUKE ANOTHER=NUKEM" 
    steps:
      - name: Checkout code 
        run: |
            echo "export variables for ${{ matrix.compose }}"
            for v in ${{ matrix.variables }}; do
                export ${v}
            done
            
            echo ${POSTGRESQL_VERSION}
            echo ${IMMORTAL}
            echo ${ANOTHER}
