name: check matrix

on:
  push:
  
  
env:
  COMPANY_NAME: "danilaworker"
  PRODUCT_NAME: "documentserver" 
  
jobs:
  build:
    name: Check docker manifest
    if: ${{ github.actor == @danilapog }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #compose: [ "postgresql.yaml" ]
        #variables: [ "POSTGRESQL_VERSION=9 IMMORTAL=FOO ANOTHER=BOO" ]
        #include: 
        #  - compose: "postgresql.yaml" 
        #    variables: "POSTGRESQL_VERSION=10 IMMORTAL=DUKE ANOTHER=NUKEM" 
         compose: [ "postgresql.yaml" ]
         variables: [ "POSTGRESQL_VERSION=10", "POSTGRESQL_VERSION=9", "POSTGRESQL_VERSION=8" ]
    steps:
      - name: Checkout code 
        run: |
            echo "export variables for ${{ matrix.compose }}"
            for v in ${{ matrix.variables }}; do
                export ${v}
            done
            
            echo ${POSTGRESQL_VERSION}
            #echo ${IMMORTAL}
            #echo ${ANOTHER}
