name: check matrix

on:
  push:
  
  
env:
  COMPANY_NAME: "danilaworker"
  PRODUCT_NAME: "documentserver" 
  
jobs:
  build:
    name: Test with ${{ matrix.name }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
         variables: ["POSTGRESQL_VERSION=9"]
         name: ["Test with postgresql 9"]
         compose: ["postgresql.yaml"]
         include: 
           - variables: "POSTGRESQL_VERSION=10 DUKE=NUKEN"
             name: "test with postgresql 10"
             compose: "postgresql.yaml"
             
           - variables: "POSTGRESQL_VERSION=11 DUKE=NUKEN"
             name: "test with postgresql 11"
             compose: "postgresql.yaml" 
             
           - variables: "POSTGRESQL_VERSION=12 DUKE=NUKEN"
             name: "test with postgresql 12"
             compose: "postgresql.yaml"
             
           - variables: "MYSQL_VERSION=8"
             name: "Test with mysql 8"
             compose: "mysql.yaml"
             
           - variables: "MYSQL_VERSION=5"
             name: "Test with mysql 5"
             compose: "mysql.yaml"
             
         #variables: [ "POSTGRESQL_VERSION=10", "IMMORTAL=9", "ANOTHER=8" ]
    steps:
      - name: Checkout ${{ matrix.variables }}
        run: |
            export config=${{ matrix.compose }}
            echo "export variables for ${{ matrix.compose }}"
            for v in ${{ matrix.variables }}; do
                export ${v}
            done
            echo config file is ${config}
            echo postgresql version is ${POSTGRESQL_VERSION}
            echo mysql version is ${MYSQL_VERSION}
            echo duke version is ${DUKE}
