name: check manifest

on:
  push:
  
  
env:
  COMPANY_NAME: "danilaworker"
  PRODUCT_NAME: "documentserver" 
  
jobs:
  build:
    name: Check docker manifest
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
        
      - name: Check manifest 
        run: |
          TESTING_IMAGE_ONE=${COMPANY_NAME}/${PRODUCT_NAME}-ee:7.2
          TESTING_IMAGE_TWO=${COMPANY_NAME}/${PRODUCT_NAME}-ee:latest
          TESTING_IMAGE_TRI=${COMPANY_NAME}/${PRODUCT_NAME}-ee:7.2.2.56
          #docker manifest inspect ${TESTING_IMAGE_ONE}
          docker manifest inspect ${TESTING_IMAGE_TWO}
          docker manifest inspect ${TESTING_IMAGE_TRI}
