name: check manifest

on:
  push:
  
  
env:
  COMPANY_NAME: "onlyoffice"
  PRODUCT_NAME: "documentserver" 
  
jobs:
  build:
    name: Check docker manifest
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with: 
          version: latest
        
      - name: check docker version
        run: |
           docker --version
           docker buildx version
        
      - name: Check manifest 
        run: |
          TESTING_IMAGE_ONE=${COMPANY_NAME}/docs-docservice-ee:7.1.0-1
          TESTING_IMAGE_TWO=${COMPANY_NAME}/docs-docservice-ee:7.2.0-1
          TESTING_IMAGE_TRI=${COMPANY_NAME}/docs-docservice-ee:7.3.3-1
          docker manifest inspect ${TESTING_IMAGE_ONE}
          docker manifest inspect ${TESTING_IMAGE_TWO}
          docker manifest inspect ${TESTING_IMAGE_TRI}
          
          
