name: lint

on:
  workflow_call:
    inputs: 
      ct_version: 
        description: 'Chart testing tool version'
        required: false
        type: string
        default: '3.8.0'
      enable_yaml_lint: 
        type: string
        description: 'Enable or disable yaml linter'
        default: 'always()'
      enable_kube_lint:
        type: string
        description: 'Enable or disable kube manifests linter'
        default: 'always()'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout chart
        uses: actions/checkout@v3
          
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2
          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true
      
      - name: Prepare unit tests environment
        run: |
           sudo apt-get update -y
           sudo apt-get install -y yamllint
           pip install yamale
           wget https://github.com/helm/chart-testing/releases/download/v${{ inputs.ct_version }}/chart-testing_${{ inputs.ct_version }}_linux_amd64.tar.gz
           wget https://github.com/danilapog/vagrant-test/blob/master/.github/kube-linter-config/.kube-linter.yaml
           tar -xvzf chart-testing_${{ inputs.ct_version }}_linux_amd64.tar.gz 
           rm -rf ./chart-testing_${{ inputs.ct_version }}_linux_amd64.tar.gz
           cp ./etc/chart_schema.yaml ./etc/lintconf.yaml .
       
      - name: Create kind cluster
        if: ${{ inputs.enable_yaml_lint }}
        uses: helm/kind-action@v1.4.0
        
      - name: lint
        if: ${{ inputs.enable_yaml_lint }}
        run: |
           ./ct lint --charts . --validate-maintainers=false
        
      - name: Test install inside kind cluster
        if: ${{ inputs.enable_yaml_lint }}
        run: | 
           ./ct install --charts .
           
      - name: Scan chart with kube-linter
        if: ${{ inputs.enable_kube_lint }}
        uses: stackrox/kube-linter-action@v1.0.4
        with:
          directory: .
          config: ./.kube-linter.yaml
          format: plain
          output-file: kube-linter.plain
