run-name: Integration test ${{ github.event.repository.name }}

on:
  workflow_call:

env: 
  K8S_CONF: 'https://raw.githubusercontent.com/danilapog/vagrant-test/master/.github/kube-linter-config/kind-config.yaml'
  
jobs:
  spin-up:
    name: integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Get kind config
        run: wget ${K8S_CONF} 
        
      - uses: azure/setup-helm@v3
        id: setup-helm
        with:
          version: 'latest' # default is latest (stable)
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
 
      - name: setup kind k8s
        id: setup-kind-k8s
        uses: helm/kind-action@v1.4.0
        with: 
          config: ./kind-config.yaml
          
      - name: Get nodes and other info
        run: | 
          for i in {1..30}; do
            echo "Get k8s workers status {i}"
            STATUS=${kubectl get nodes | grep -o NotReady)
            if [[ -z "${STATUS}" ]]; then
              echo "K8s workers is ready. Continue...
            fi
          done
          kubectl get nodes
