run-name: Integration test ${{ github.event.repository.name }}

on:
  workflow_call:

env: 
  K8S_CONF: 'https://raw.githubusercontent.com/danilapog/vagrant-test/master/.github/kube-linter-config/kind-config.yaml'
  
jobs:
  spin-up:
    name: integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Get kind config
        run: wget ${K8S_CONF} 
        
      - uses: azure/setup-helm@v3
        id: setup-helm
        with:
          version: 'latest' # default is latest (stable)
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
 
      - name: setup kind k8s
        id: setup-kind-k8s
        uses: helm/kind-action@v1.4.0
        with: 
          config: ./kind-config.yaml
          
      - name: Get nodes status
        timeout-minutes: 2
        run: | 
          for i in {1..10}; do
            echo "Get k8s workers status ${i}"
            STATUS=$(kubectl get nodes | grep -o NotReady 2> /dev/null)
            if [[ -z "${STATUS}" ]]; then
              echo "K8s workers is ready. Continue..."
              k8s_ready='true'
              break
            else
              echo ${STATUS}
              sleep 20
            fi
          done
        shell: bash
          
      - name: Get nodes status 
        run: |
          kubectl get nodes
          kubectl get storagesclass
