name: vagrant-up

on: [push]

env:
  VAGRANT_VERSION: 2.3.2
defaults:
  run:
    working-directory: 'vagrant-test'

jobs:
  vagrant-up:
    name: Test on ${{ matrix.boxes }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        boxes: 
          - generic/centos7
          - generic/debian9
          - generic/debian10
          - generic/debian11
          - generic/ubuntu1604
          - generic/ubuntu1804
          - generic/ubuntu2004
          - generic/ubuntu2204
 
    steps:
    - name: Checkout code      
      uses: actions/checkout@v2
      with: 
        path: 'vagrant-test'
 
    - name: Set up Python 3.
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install virtual-box+vagrant.
      run: |

           # ################## #
           # setting up vagrant #
           # ################## #
          
           mkdir -p ./vagrant
           wget https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}-1_amd64.deb ./vagrant/vagrant_amd64.deb
           dpkg -i ./vagrant/vagrant_amd64.deb

           # ###################### #
           # setting up virtual-box #
           # ###################### #
           
           wget http://download.virtualbox.org/virtualbox/7.0.2/virtualbox-7.0_7.0.2-154219~Ubuntu~jammy_amd64.deb ./vagrant/virtualbox_amd64.deb
           dpkg -i virtualbox_amd64.deb
           apt-get install linux-headers-$(uname -r)


    - name: Replace os image
      run: gsed -i 's!%BOX_IMAGE%!${{ matrix.boxes }}!' Vagrantfile

    - name: Show Vagrant version
      run: vagrant --version

    - name: Run vagrant up
      run: vagrant up
    
    - name: remove postfix on Debian
      run: vagrant ssh -c "sudo apt-get remove postfix -y"
      if: |
          matrix.boxes == 'generic/debian9' ||
          matrix.boxes == 'generic/debian10' || 
          matrix.boxes == 'generic/debian11'
      
    - name: Set hostname 
      run: vagrant ssh -c "echo '127.0.0.1 host4test' | sudo tee -a /etc/hosts"
     
    - name: download install sctipt
      run: vagrant ssh -c "sudo wget https://download.onlyoffice.com/install/workspace-install.sh"

    - name: run script
      run: vagrant ssh -c "sudo bash -c 'export RABBITMQ_NODENAME=rabbit@localhost' ; sudo echo 'N' | sudo bash workspace-install.sh --skiphardwarecheck true --makeswap false"

