---
name: Scanning DocSpace with ZAP

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Set branch for which OCI script will be used for deploy'
        type: string
        required: true
      version:
        description: 'Set DocSpace version that will be deployed'
        type: string
        required: true
jobs:
  zap:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    name: Scan DocSpace with zap
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: build-tools
          ref: ${{ github.event.inputs.branch }}

      - name: check
        run: |
           echo ${{ github.event.inputs.version }}
           echo ${{ github.event.inputs.branch }}
          
          
