name: vagrant-up

on: [push]

defaults:
  run:
    working-directory: 'vagrant-test'

jobs:
  vagrant-up:
    name: Test on ${{ matrix.boxes }}
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        boxes: 
        #- generic/centos7
          - generic/debian9
          - generic/debian10
          - generic/debian11
          - generic/ubuntu1604
          - generic/ubuntu1804
          - generic/ubuntu2004
            # - generic/ubuntu2204
 
    steps:
    - name: Checkout code      
      uses: actions/checkout@v2
      with: 
        path: 'vagrant-test'
 
    - name: Set up Python 3.
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install test dependencies.
      run: |
        pip3 install ansible 
        brew install gnu-sed

    - name: Replace os image
      run: gsed -i 's!%BOX_IMAGE%!${{ matrix.boxes }}!' Vagrantfile

    - name: Show Vagrant version
      run: vagrant --version

    - name: Run vagrant up
      run: vagrant up

    - name: download install sctipt
      run: vagrant ssh -c "wget https://download.onlyoffice.com/install/workspace-install.sh"

    - name: run script
      run: vagrant ssh -c "echo 'N' | sudo bash workspace-install.sh --skiphardwarecheck true --makeswap false"

