name: Scripts test
  
run-name: Check ort secret
on:
  push:
jobs:
  vagrant-up:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        id: check
        env:
          SECRET: ${{ secrets.MY_ORG_SECRET }}
        run: |
           if [[ "${SECRET}" == "foo" ]]; then
             exit 0
           else 
             exit 1
           fi
