name: "Build test image"

run-name: >-
  Build test image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify full tag (ex. 1.0.0-rc.12)'
        type: string
        required: false

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: set env
      shell: bash
      run: |
         echo "COMMIT_SHA=$(git rev-parse HEAD)" >> "$GITHUB_ENV"
         echo "TAG=1.5.1-rc.${{ github.run_number }}" >> "$GITHUB_ENV"

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        pull: true
        no-cache: true
        tags: test/nginx:123
        build-args: |
          COMMIT_SHA=${{ env.COMMIT_SHA }}

    - name: check
      run: |
        docker run --name mytest test/nginx:123
        docker exec mytest env
