name: 4testing multiarch-build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
      - name: check
        id: build
        env: 
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          VERSION: v1.0.0
          BRANCH: release/v1.0.0
        run: |
           gh workflow run manual-action.yaml \
                 --repo \${{ github.repository }} \
                 --ref \${BRANCH} \
                 -f branch=${BRANCH} \
                 -f version=${VERSION}
                 
        shell: bash

