name: 4testing multiarch-build

run-name: >
    Test on branch ${{ github.event.inputs.branch }} ${{ github.event.inputs.branch }}
on:
  push:
  workflow_dispatch: 
    inputs:
      branch:
        description: 'branch release/v1.0.0 for example'
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["release/v1.0.0", "develop"]
    outputs:
      branch: ${{ steps.build.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: build-tools
          ref: ${{ github.event.inputs.branch }}
      
      - name: check
        id: build
        run: |
           set -e 
           ls -l ./build-tools/
           vetka="${{ matrix.branch }}"
           if [[ ${vetka} =~ release ]]; then
            # Move build tag to output for use it with zap scanning for non-develop branches
            echo "This is release, send branch name to output"
            echo "branch=${vetka}" >> "$GITHUB_OUTPUT"
           fi
        shell: bash

  zap:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    needs: [build]
    if: ${{ startsWith(needs.build.outputs.branch, 'release/') }}
    name: Scan DocSpace with zap
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: build-tools
          ref: ${{ needs.build.outputs.branch }}

      - name: check
        run: ls build-tools/
