name: vagrant-up

on: [push]

env: 
  BOX_DISTRIBUTION: generic

defaults:
  run:
    working-directory: 'vagrant-test'

jobs:
  vagrant-up:
    name: "${{ matrix.boxes }}-${{ matrix.installation }} installation"
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        boxes: 
          - centos7
          - debian9
          - debian10
          - debian11
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
          - ubuntu2204
        installation: 
          - default
          - docker
        exclude:
          - boxes: debian9
            installation: docker
          - boxes: centos7
            installation: docker
          - boxes: ubuntu1604
            installation: docker

    steps:
    - name: Checkout code      
      uses: actions/checkout@v2
      with: 
        path: 'vagrant-test'
 
    - name: Set up Python 3.
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install test dependencies.
      run: brew install gnu-sed

    - name: Replace os image
      run: gsed -i "s!%BOX_IMAGE%!$BOX_DISTRIBUTION/${{ matrix.boxes }}!" Vagrantfile

    - name: setting-up Docker install if present
      run: |

        if [ ${{ matrix.installation }} == 'docker' ]; then
          gsed -i "s!'./install.sh'!./install.sh', :args => \"-d true\"!" Vagrantfile
        fi
 

    - name: Show Vagrant version
      run: vagrant --version

    - name: Run vagrant up
      run: vagrant up

      #- name: remove postfix on Debian
      #run: vagrant ssh -c "sudo apt-get remove postfix -y ; sudo apt-get install dialog apt-utils -y"
      #if: |
      #  matrix.boxes == 'generic/debian9' ||
      #  matrix.boxes == 'generic/debian10' || 
      #  matrix.boxes == 'generic/debian11' || 
      #  matrix.boxes == 'generic/ubuntu1804' ||
      #  matrix.boxes == 'generic/ubuntu2004' ||
      #  matrix.boxes == 'generic/ubuntu2204'
    
      #- name: check exit code
      #run: vagrant ssh -- /bin/false ; echo $? 
    
    #- name: Set hostname
    #  run: vagrant ssh -- echo '127.0.0.1 host4test' | sudo tee -a /etc/hosts ; mkdir -p ./scripts
    
      #- name: Download scripts
      #run: vagrant ssh -- "wget https://download.onlyoffice.com/install/workspace-install.sh -P /home/vagrant/"

      #- name: Install
      #run: vagrant ssh -- echo 'N' \|\ sudo bash /home/vagrant/workspace-install.sh --skiphardwarecheck true --makeswap false >> output.logs

      #- name: Check code
      #run: |
      #     vagrant ssh -c "cat /home/vagrant/output.logs | grep "

     #- name: Check is that hosts is correct
     # run: vagrant ssh -c "sudo cat /etc/hosts ; sudo cat /etc/hostname"
     
    #- name: download install sctipt
    # run: vagrant ssh -c "sudo wget https://download.onlyoffice.com/install/workspace-install.sh"

