name: Shell script testing

#on:
  #push:

#on:
#  pull_request:
#    types: [opened, reopened, edited]
#    paths:
#    - 'sub-project/**'
#on:
#  schedule:
#    - cron: '00 21 * * 6'  # At 21:00 on Saturday.
    
env: 
  BOX_DISTRIBUTION: generic
  RUNNER_IMAGE: ubuntu-22-04-x64
  RUNNER_REGION: fra1
  RUNNER_SIZE: s-4vcpu-8gb-intel

jobs:
  spin-up:
    name: Make ${{ matrix.name }}
    runs-on: ubuntu-latest
    outputs: 
      instance-name: ${{ steps.get-name.outputs.name }}
    strategy:
      fail-fast: false
      matrix:
        name: 
          - gha-runner-centos7-${{ github.run_id }}-${{ github.run_number }}
            #- gha-runner-centos8s-${{ github.run_id }}-${{ github.run_number }}
            #- gha-runner-centos9s-${{ github.run_id }}-${{ github.run_number }}
            #- gha-runner-debian9-${{ github.run_id }}-${{ github.run_number }}
            #- gha-runner-debian10-${{ github.run_id }}-${{ github.run_number }}
            #- gha-runner-debian11-${{ github.run_id }}-${{ github.run_number }}
            #- gha-runner-ubuntu1604-${{ github.run_id }}-${{ github.run_number }}
            #- gha-runner-ubuntu1804-${{ github.run_id }}-${{ github.run_number }}
            #- gha-runner-ubuntu2004-${{ github.run_id }}-${{ github.run_number }}
            #- gha-runner-ubuntu2204-${{ github.run_id }}-${{ github.run_number }}
    steps:
    - name: cheeck action
      run: echo "hello" 
