name: Upload Release Files to AWS S3

on:
  release:
    types: [published]

jobs:
  upload-release:
    name: "Upload Release Files to AWS S3"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
