name: 4testing multiarch-build

run-name: >
    Test on branch ${{ github.event.inputs.branch }} ${{ github.event.inputs.branch }}
on:
  push:
  workflow_dispatch: 
    inputs:
      branch:
        description: 'branch release/v1.0.0 for example'
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["release/v1.0.0", "develop"]
        fail-fast: false
    outputs:
      branch: ${{ steps.build.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: build-tools
          ref: ${{ github.event.inputs.branch }}
      
      - name: check
        id: build
        env: 
          VERSION: ${{ github.event.inputs.branch || 'develop' }}
        run: |
           exit 1
           echo ${VERSION}
           echo ${{ github.event.repository.name }}
           echo ${{ github.action_repository }}
           echo ${{ github.repository }}
        shell: bash

      - name: checkanother
        run: echo hello
