name: vagrant-up

on: [push]

env: 
  BOX_DISTRIBUTION: generic

defaults:
  run:
    working-directory: 'vagrant-test'

jobs:
  spin-up-droplet:
    name: ${{ matrix.boxes }}
    uses: oxide-one/worm/.github/workflows/spinup.yaml@main
    strategy:
      matrix:
        boxes: 
          - centos7-runner
          - debian9-runner
          - debian10-runner
          - debian11-runner
          - ubuntu1604-runner
          - ubuntu1804-runner
          - ubuntu2004-runner
          - ubuntu2204-runner
          
    with:
      image: ubuntu-20-04-x64
      size: s-4vcpu-8gb-intel
      name: gha-${{ github.run_id }}-${{ github.run_number }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
      do-access-token: ${{ secrets.DO_ACCESS_TOKEN }}

  vagrant-up:
    needs: spin-up-droplet
    name: "${{ matrix.boxes }}-${{ matrix.installation }} installation"
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        boxes: 
          - centos7
          - debian9
          - debian10
          - debian11
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
          - ubuntu2204
        #installation: 
        #  - default
        #  - docker
        #exclude:
        #  - boxes: debian9
        #    installation: docker
        #  - boxes: centos7
        #    installation: docker
        #  - boxes: ubuntu1604
        #    installation: docker

    steps:
    - name: Checkout code      
      uses: actions/checkout@v2
      with: 
        path: 'vagrant-test'
 
    - name: Set up Python 3.
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Replace os image
      run: sed -i "s!%BOX_IMAGE%!$BOX_DISTRIBUTION/${{ matrix.boxes }}!" Vagrantfile

    - name: setting-up Docker install if present
      run: |
        if [ ${{ matrix.installation }} == 'docker' ]; then
          gsed -i "s!'./install.sh'!'./install.sh', :args => \"-d true\"!" Vagrantfile
        fi
 
    - name: Show Vagrant version
      run: vagrant --version

    - name: Run vagrant up
      run: vagrant up
  
  tear-down-droplet:
    needs: 
      - vagrant-up
    name: Spin Down Droplet
    if: always() 
    uses: oxide-one/worm/.github/workflows/teardown.yaml@main
    with:
      name: gha-${{ github.run_id }}-${{ github.run_number }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
      do-access-token: ${{ secrets.DO_ACCESS_TOKEN }}    
